market/conversation/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import *
from .models import *
app_name = 'conversations'


urlpatterns=[
    path('new/<int:item_pk>/',views.new_conversation,name='new'),
    path('',views.inbox,name='inbox'),
    path('<int:pk>/',views.detailing,name='detailing'),
]

market/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import *
app_name = 'core'
urlpatterns=[
    path('',views.index,name="index"),
    path('contact/',views.contact,name="contact"),
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm),name='login'),
    path('logout/',views.logoutview,name='logout'),
]

market/item/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = 'item'
urlpatterns=[
    path('<int:pk>/',views.detail,name='detail'),
    path('new/',views.new,name='new'),
    path('browse/',views.browse,name='browse'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/edit/',views.edit,name='edit'),
    path('newcat/',views.newcat,name='newcat'),
]

market/market/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('core.urls')),
    path('items/',include('item.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

market/item/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural='Categories'
        
    
    def __str__(self):
        return self.name


class Item(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True ,null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images',blank=True,null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User,related_name='items',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    cat = models.ForeignKey(Category,related_name='items',on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    @property
    def objimage(self):
        if(self.image):
            return self.image.url
        return ''

market/item/forms.py
from django import forms
from .models import *
from django.core.exceptions import ValidationError

INPUT_CLASSES='w-1/2 py-4 px-6 rounded-xl border'


def validate_text(category_name):
    category_name=category_name.lower()
    exist_cat = Category.objects.all()
    for catt in exist_cat:
        if catt.name.lower()==category_name:
            return True
    return False

class NewCatForm(forms.ModelForm):
    """class Meta:
        model=Category
        fields = ('name',)
        widgets={
            'name':forms.TextInput(attrs={
                'class':INPUT_CLASSES
            }),
        }"""
    class Meta:
        model = Category
        fields=('name',)
        widgets={
            'name':forms.TextInput(attrs={
                'class':INPUT_CLASSES
            }),
        }

    name = forms.CharField(max_length=255)

    def clean(self):
        cleaned_data= super(NewCatForm,self).clean()
        catname = cleaned_data.get('name')
        if validate_text(catname):
            self.add_error("name","This Category already exists")  
        return cleaned_data



class NewItemForm(forms.ModelForm):
    class Meta:
        model =Item
        fields=('cat','name','description','price','image')
        widgets={
            'cat':forms.Select(attrs={
                'class':INPUT_CLASSES
            }),
            'name':forms.TextInput(attrs={
                'class':INPUT_CLASSES
            }),
            'description':forms.Textarea(attrs={
                'class':INPUT_CLASSES
            }),
            'price':forms.TextInput(attrs={
                'class':INPUT_CLASSES
            }),
            'image':forms.FileInput(attrs={
                'class':INPUT_CLASSES
            }),

            
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model =Item
        fields=('name','description','price','image','is_sold')
        widgets={
            
            'name':forms.TextInput(attrs={
                'class':INPUT_CLASSES
            }),
            'description':forms.Textarea(attrs={
                'class':INPUT_CLASSES
            }),
            'price':forms.TextInput(attrs={
                'class':INPUT_CLASSES
            }),
            'image':forms.FileInput(attrs={
                'class':INPUT_CLASSES
            }),

            
        }

market/item/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.db.models import Q
from .models import *
from .forms import *

def validate_text(category_name):
    category_name=category_name.lower()
    exist_cat = Category.objects.all()
    for catt in exist_cat:
        if catt.name.lower()==category_name:
            raise ValidationError('Category Already Exists!')
            return redirect('dashboard:index')

def browse(request):
    query = request.GET.get('query','')
    category_id = request.GET.get('category',0)
    items = Item.objects.filter(is_sold=False)
    categories =  Category.objects.all()
    
    if query:
        items = items.filter(Q(name__icontains=query) |  Q(description__icontains=query))
    if category_id:
        items = items.filter(cat_id=category_id)
    return render(request, 'item/browse.html',{
        'items':items,
        'query':query, 
        'categories':categories,
        'category_id':int(category_id),
        } )

def detail(request,pk):
    item = get_object_or_404(Item,pk=pk)
    related_items = Item.objects.filter(cat=item.cat,is_sold=False).exclude(pk=pk)[0:3] 
    return render(request,'item/detail.html',{'item':item,'related_items':related_items})

@login_required
def new(request):
    if(request.method=='POST'):
        form = NewItemForm(request.POST,request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by=request.user
            item.save()
            return redirect('item:detail',pk=item.id)

    else:    
        form = NewItemForm()


        return render(request,'item/form.html',{'form':form,'title':'New Item'})


@login_required
def newcat(request):
    if(request.method=='POST'):
        form = NewCatForm(request.POST)
        if form.is_valid():
            form.save()
            #cattemp = form.save(commit=False)
            #cattemp.save()
            return redirect('dashboard:index')
        else:
            #form=NewCatForm()
            return render(request,'item/newcat.html',{'form':form,'title':'Add New Category'})
    else:
        form = NewCatForm()
        return render(request,'item/newcat.html',{'form':form,'title':'Add New Category'})
            
            




@login_required
def delete(request,pk):
    item =get_object_or_404(Item,pk=pk,created_by=request.user)
    item.delete()
  
    return redirect('dashboard:index')

@login_required
def edit(request,pk):
    item =get_object_or_404(Item,pk=pk,created_by=request.user)
    if(request.method=='POST'):
        
        form = EditItemForm(request.POST,request.FILES,instance=item)
        if form.is_valid():
            form.save()
            return redirect('item:detail',pk=item.id)

    else:    
        form = EditItemForm(instance=item)


        return render(request,'item/form.html',{'form':form,'title':'Edit Item'})
    

market/item/templates/item/browse.html
{%extends 'core/base.html' %}
{%block title %}Browse Items{%endblock%}  

{%block content%}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{%url 'item:browse' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{query}}" placeholder="Find an item with specific name...."> 
                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
            </form>

            <hr class="my-6">
            <p class="font-semibold">Categories</p>
            <ul>
                {%for category in categories%}
                    <li class="px-2 py-2 rounded-xl{%if category.id == category_id%} bg-gray-200{%endif%}">
                        <a href="{% url 'item:browse' %}?query={{ query }}&category={{category.id}}">{{category.name}}</a>
                    </li>
                {%endfor%}
            </ul>
            <hr class="my-6">
            <p class="font-semibold">Clear Filters</p>
            <ul>
                <li>
                    <a href="{% url 'item:browse' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a>
                </li>
            </ul>
        </div>  
        
        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3 ">
                {% for obj in items %}
                    <div>
                        <a href="{% url 'item:detail' obj.id %}">
                            <div>
                                

                                <img src="{{ obj.objimage }}" class="rounded-t-xl">
                            </div> 
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="2xl" >{{obj.name}}</h2>
                                <p class="text-gray-500" >Price: {{obj.price}}</p>
                            </div>
                        </a>
                    </div>
                {%endfor%}
        </div>
            
        </div>
    </div>



{%endblock%}

market/item/templates/item/detail.html
{%extends 'core/base.html' %}
{%block title %}{{item.name }}{%endblock%}


{%block content%}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{item.objimage}}" class="rounded-xl">

    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
       <h1 class="mb-6 text-3xl">{{item.name }}</h1> 
       <p class="text-gray-500"><strong>Price: </strong>{{item.price}}</p>
       <p class="text-gray-500"><strong>Seller: </strong>{{item.created_by.username}}</p>
        {% if item.description %}
            <p class="text-gray-700"><strong class="text-gray-500">Description: </strong><br>{{item.description}}</p>
        {%endif%}
        {%if request.user == item.created_by%}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>Your Item</p>
                <a href="{%url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
                <a href="{%url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-green-500 text-white rounded-xl">Edit</a>
            </div>
        {%else%}
            <a href = "{%url 'conversations:new' item.id%}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact Seller</a>
        {%endif%}
    </div>

</div>  
<div class="mt-6 px-6 py-12 bg-gray-200 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related Items </h2>
        <div class="grid grid-cols-3 gap-3 ">
            {% for obj in related_items %}
                <div>
                    <a href="{% url 'item:detail' obj.id %}">
                        <div>
                            

                            <img src="{{ obj.objimage }}" class="rounded-t-xl">
                        </div>
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="2xl" >{{obj.name}}</h2>
                            <p class="text-gray-500" >Price: {{obj.price}}</p>
                        </div>
                    </a>
                </div>
            {%endfor%}
    </div>
</div>
          


{%endblock%}
 

market/item/templates/item/form.html
{%extends 'core/base.html' %}

{%block title%}{{title}}{%endblock%}

{%block content%}
    <h1 class="mb-6 text-3xl">{{title}}</h1>
    <form method="post" action="." enctype="multipart/form-data">
        {%csrf_token%}
        <div class="mt-6 mb-6">
            <p class="mb-6">Cant find category? Add category below</p>
            <a href="#" class="px-4 py-4 mt-6 mb-6font-semibold bg-amber-100 rounded-xl text-red-600 hover:bg-amber-500 "> Click Here </a>
        </div>
        <div class="space-y-4">
            {{form.as_p}}

        </div>

        {% if form.errors or form.non_field_errors%}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form%}
                    {{field.errors}}
                {% endfor %}
                {{form.non_field_errors}}
            </div>
        {%endif%}
        <button class="py-4 px-8 mt-6 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>

{%endblock%}

market/item/templates/item/newcat.html
{%extends 'core/base.html' %}

{%block title%}{{title}}{%endblock%}

{%block content%}
    <h1 class="mb-6 text-3xl">{{title}}</h1>
    <form method="post" action=".">
        {%csrf_token%}
        
        <div class="space-y-4">
            <div class="w-1/2 py-4 px-6 rounded-xl border">
                <h1>Name: {{form.name}}</h1>
            </div>
        </div>

        {% if form.errors or form.non_field_errors%}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form%}
                    {{field.errors}}
                {% endfor %}
                {{form.non_field_errors}}
            </div>
        {%endif%}

        
        <button class="py-4 px-8 mt-6 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>

{%endblock%}