market/conversation/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import *
from .models import *
app_name = 'conversations'


urlpatterns=[
    path('new/<int:item_pk>/',views.new_conversation,name='new'),
    path('',views.inbox,name='inbox'),
    path('<int:pk>/',views.detailing,name='detailing'),
]

market/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import *
app_name = 'core'
urlpatterns=[
    path('',views.index,name="index"),
    path('contact/',views.contact,name="contact"),
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm),name='login'),
    path('logout/',views.logoutview,name='logout'),
]

market/dashboard/urls.py
from django.urls import path,include
from . import views
app_name ='dashboard'

urlpatterns=[
    path('',views.index,name='index'),
]

market/item/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = 'item'
urlpatterns=[
    path('<int:pk>/',views.detail,name='detail'),
    path('new/',views.new,name='new'),
    path('browse/',views.browse,name='browse'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/edit/',views.edit,name='edit'),
    path('newcat/',views.newcat,name='newcat'),
]

market/market/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('core.urls')),
    path('items/',include('item.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

market/core/models.py
from django.db import models

# Create your models here.

market/core/forms.py
from django import forms
from django.contrib.auth.forms import *
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    

    class Meta:
        model = User
        fields =('username','email','password1','password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your Username',
        'class':'w-1/2 py-4 px-6 rounded-xl'

    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'something@something.com',
        'class':'w-1/2 py-4 px-6 rounded-xl'

    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Choose a password',
        'class':'w-1/2 py-4 px-6 rounded-xl'

    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'',
        'class':'w-1/2 py-4 px-6 rounded-xl'

    }))

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter your username',
        'class':'w-1/2 py-4 px-6 rounded-xl'

    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Enter your password',
        'class':'w-1/2 py-4 px-6 rounded-xl'

    }))

market/core/views.py
from django.shortcuts import render,redirect
from item.models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

from .forms import *

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6] 
    categories = Category.objects.all()

    return render(request,'core/index.html',{'categories': categories,'items':items})

def contact(request):
    return render(request,'core/contact.html')

@login_required
def logoutview(request):
    logout(request)
    return redirect('core:index')

def signup(request):
    if request.method=='POST':
        form=SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()
    return render(request,'core/signup.html',{'form':form})

market/core/templates/core/base.html
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https:/cdn.tailwindcss.com"></script>
        <title>{%block title%}{%endblock%}|Online Market</title>

    </head>
    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class ="text-xl font-semibold">JOKES MARKET</a>
            <div class = "space-x-6">
                <a href="{%url 'item:browse'%}" class="text-lg font-semibold hover:text-gray-500"> Browse</a>
                <a href="{% url 'item:new'%}" class="text-lg font-semibold hover:text-gray-500"> New Item</a>
                {% if request.user.is_authenticated %}
                    
                    <a href="{% url 'conversations:inbox'  %}" class="px-6 py-3 text-lg font-semibold bg-amber-200 rounded-xl text-red-600 hover:bg-amber-500 ">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-6 py-3  font-semibold bg-amber-200 text-red-600 rounded-xl hover:bg-amber-500 ">Dashboard</a>
                    <a href="{% url 'core:logout' %}" class="px-6 py-3 font-semibold bg-amber-200 text-red-600 rounded-xl hover:bg-amber-500">Logout</a>

                {%else%}

                    <a href="{% url 'core:signup'%}" class="px-6 py-3 text-lg font-semibold bg-amber-200 rounded-xl text-red-600 hover:bg-amber-500 ">Sign Up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3  font-semibold bg-amber-200 text-red-600 rounded-xl hover:bg-amber-500 ">Login</a>
                {%endif%}
            </div>
        </nav>
        <div class="px-6 py-6">
            {%block content%}
            {%endblock%}
        </div>
        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-500">This is a practice project</h3>
                <p>yap session yap yap yap</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-500">Menu</h3>
                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{%url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact Us</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of Use</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>

                </ul>

            </div>
    
        </footer>

       
    </body>
    
</html>

market/core/templates/core/contact.html
{% extends 'core/base.html' %}
{%block title%}ContactPage{%endblock%}
{%block content%}
<h1>Contact Details</h1>
{%endblock%}

market/core/templates/core/index.html
{% extends 'core/base.html' %}
{%block title%}FrontPage{%endblock%}
{%block content%}

    <div class="mt-6 px-6 py-12 bg-gray-200 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">LATEST UNSOLD ITEMS </h2>
            <div class="grid grid-cols-3 gap-3 ">
                {% for obj in items %}
                    <div>
                        <a href="{% url 'item:detail' obj.id %}">
                            <div>
                                

                                <img src="{{ obj.objimage }}" class="rounded-t-xl">
                            </div>
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="2xl" >{{obj.name}}</h2>
                                <p class="text-gray-500" >Price: {{obj.price}}</p>
                            </div>
                        </a>
                    </div>
                {%endfor%}
        </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-200 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">CATEGORIES </h2>
            <div class="grid grid-cols-3 gap-3 ">
                {%for cat in categories%}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="2xl" >{{cat.name}}</h2>
                            <p class="text-gray-500" >{{cat.items.count}} items</p>
                        </div> 
                    </a>
                </div>


                {%endfor%}
            </div>
    </div>
    
{%endblock%}

market/core/templates/core/login.html
{% extends 'core/base.html' %}

{%block title%}Login{%endblock%}

{%block content%}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Login</h1>
        <form method = "post" action=".">
            {% csrf_token %}
           
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{form.username}}
            </div>
          
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{form.password}}
            </div>
        

            {% if form.errors or form.non_field_errors%}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form%}
                        {{field.errors}}
                    {% endfor %}
                    {{form.non_field_errors}}
                </div>
            {%endif%}
 
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
</div>

{%endblock%}

market/core/templates/core/signup.html
{% extends 'core/base.html' %}

{%block title%}Signup Page{%endblock%}

{%block content%}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>
        <form method = "post" action=".">
            {% csrf_token %}
           
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{form.username}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Email ID</label><br>
                {{form.email}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{form.password1}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Confirm Password</label><br>
                {{form.password2}}
            </div>

            {% if form.errors or form.non_field_errors%}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form%}
                        {{field.errors}}
                    {% endfor %}
                    {{form.non_field_errors}}
                </div>
            {%endif%}
 
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
</div>

{%endblock%}